services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      CLIENT_URL: http://localhost:4200
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: gestion_escolar
      DB_USER: postgres
      DB_PASSWORD: root
      JWT_SECRET: clave-secreta-desarrollo
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: gestion_escolar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
